apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resilientcommerce-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/likith1231/Aethermed.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: resilientcommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
